micronaut:
  application:
    name: oda-streamelements-service
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: ${JWKS_URI}
  executors:
    command-listener:
      type: fixed
      nThreads: 1
    config-listener:
      type: fixed
      nThreads: 1
    event-listener:
      type: fixed
      nThreads: 1
