micronaut:
  application:
    name: oda-streamelements-service
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
  executors:
    command-listener:
      type: fixed
      nThreads: 1
    config-listener:
      type: fixed
      nThreads: 1
    event-listener:
      type: fixed
      nThreads: 1
# infinispan:
#   client:
#     hotrod:
#       server:
#         host: 10.43.81.28
#         port: 11222
#       security:
#         enabled: true
#         authentication:
#           username: admin
#           password: password
